version: '3.9'

services:
  raketa:
    container_name: raketa
    build:
      dockerfile: Dockerfile
    command: ./wait-for-postgres.sh raketadb ./bin/api
    ports:
      - 50052:50052
      - 9090:9090
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - raketadb
    restart: always
    networks:
      - backend
  
  raketadb:
    image: postgres:15.1
    container_name: raketadb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=raketadb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=raketadb
      - PGDATA = "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./migrations/000001_raketadb.up.sql:/docker-entrypoint-initdb.d/1_initdb.sql
      - ./migrations/000002_raketadb.up.sql:/docker-entrypoint-initdb.d/2_initdb.sql
      - ./pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - backend

volumes:
  pgdata:
networks:
  backend:
    driver: bridge
